language: php

sudo: true

addons:
  apt:
    packages:
      - tidy

# Technique taken from https://github.com/GSA/asis/blob/e59f23ccc49fdc54fcbe5b12eb7b1dea196c5f34/.travis.yml
before_install:
  - travis_retry curl -O https://download.elasticsearch.org/elasticsearch/elasticsearch/elasticsearch-1.7.2.deb && sudo dpkg -i elasticsearch-1.7.2.deb && true
  - 'echo ''script.disable_dynamic: false'' | sudo tee --append /etc/elasticsearch/elasticsearch.yml'
  - 'echo ''index.number_of_shards: 1'' | sudo tee --append /etc/elasticsearch/elasticsearch.yml'
  - sudo service elasticsearch start
  - pip install --user codecov

env:
  global:
    - DB=MYSQL CORE_RELEASE=3.1
    - MODULE_PATH=elastica

matrix:
  #allow_failures:
  #  - php: hhvm-nightly
  include:
    - php: 5.5
      env: DB=SQLITE
    - php: 5.5
      env: DB=MYSQL

    # Run tests in parallel in order to avoid hitting the 50 min time limit
    - php: 5.6
      env: DB=SQLITE TESTS=1
    - php: 5.6
      env: DB=SQLITE TESTS=2
    - php: 5.6
      env: DB=SQLITE TESTS=3
    - php: 5.6
      env: DB=SQLITE TESTS=4
    - php: 5.6
      env: DB=SQLITE TESTS=5
    - php: 5.6
      env: DB=SQLITE TESTS=6
    - php: 5.6
      env: DB=SQLITE TESTS=7
    - php: 5.6
      env: DB=SQLITE TESTS=8
    - php: 5.6
      env: DB=SQLITE TESTS=9
    - php: 5.6
      env: DB=SQLITE TESTS=10
    - php: 5.6
      env: DB=SQLITE TESTS=11


before_script:
  - phpenv rehash
  - composer self-update || true
  - git clone git://github.com/silverstripe-labs/silverstripe-travis-support.git ~/travis-support
  - php ~/travis-support/travis_setup.php --source `pwd` --target ~/builds/ss
  - cd ~/builds/ss

script:
  - vendor/bin/phpunit -c $MODULE_PATH/phpunit.xml $MODULE_PATH/tests
  # Execute tets with coverage.  Do this for a small tests in one go and long tests one by one
  - "if [ \"$TESTS\" = \"1\" ]; then vendor/bin/phpunit --coverage-clover=coverage.clover $MODULE_PATH/tests/short; fi"
  - "if [ \"$TESTS\" = \"2\" ]; then vendor/bin/phpunit --coverage-clover=coverage.clover $MODULE_PATH/tests/long/AggregationUnitTest.php; fi"
  - "if [ \"$TESTS\" = \"3\" ]; then vendor/bin/phpunit --coverage-clover=coverage.clover $MODULE_PATH/tests/long/ElasticaServiceTest.php; fi"
  - "if [ \"$TESTS\" = \"4\" ]; then vendor/bin/phpunit --coverage-clover=coverage.clover $MODULE_PATH/tests/long/ElasticSearcherUnitTest.php; fi"
  - "if [ \"$TESTS\" = \"5\" ]; then vendor/bin/phpunit --coverage-clover=coverage.clover $MODULE_PATH/tests/long/ElasticSearchPageControllerTest.php; fi"
  - "if [ \"$TESTS\" = \"6\" ]; then vendor/bin/phpunit --coverage-clover=coverage.clover $MODULE_PATH/tests/long/ElasticSearchPageTest.php; fi"
  - "if [ \"$TESTS\" = \"7\" ]; then vendor/bin/phpunit --coverage-clover=coverage.clover $MODULE_PATH/tests/long/ElasticSearchPage_Validator_Test.php; fi"
  - "if [ \"$TESTS\" = \"8\" ]; then vendor/bin/phpunit --coverage-clover=coverage.clover $MODULE_PATH/tests/long/FindElasticaSearchPageExtensionTest.php; fi"
  - "if [ \"$TESTS\" = \"9\" ]; then vendor/bin/phpunit --coverage-clover=coverage.clover $MODULE_PATH/tests/long/QueryGeneratorTest.php; fi"
  - "if [ \"$TESTS\" = \"10\" ]; then vendor/bin/phpunit --coverage-clover=coverage.clover $MODULE_PATH/tests/long/SearchableFieldTest.php; fi"
  - "if [ \"$TESTS\" = \"11\" ]; then vendor/bin/phpunit --coverage-clover=coverage.clover $MODULE_PATH/tests/long/SearchableTest.php; fi"
  - "if [ \"$TESTS\" = \"10\" ]; then vendor/bin/phpunit --coverage-clover=coverage.clover $MODULE_PATH/tests/long/SearchAndIndexingTest.php; fi"
  - "if [ \"$TESTS\" = \"11\" ]; then vendor/bin/phpunit --coverage-clover=coverage.clover $MODULE_PATH/tests/long/TranslatableUnitTest.php; fi"
